name: build using maven
on:
  workflow_dispatch:


jobs:
  build:
      name: build and package
      runs-on: ubuntu-latest  # Maven comes installed by default with latest version
      steps:
        - name: checkout
          uses: actions/checkout@v3
          with: 
            repository: aswaray1978/java-db-Login
        
        - name: setup JDK 8
          uses: actions/setup-java@v3
          with:
             distribution: 'temurin' # See 'Supported distributions' for available options
             java-version: '8'
        
        - name: build package
          run: mvn clean package #Clean source code, perform JUnit testing & create war file 
                                 # target/ directory is created after war file created
        - name: create dir
          run: mkdir package && cp target/*.war package/application.war
                # Create package directory and copying war file from /target to /package/ and 
                # renaming it application.war. Once complete gitub runner will clean up and terminate
        
        - name: upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: package #path/to/artifact
        
  deploy-package:        
          name: deploy-to-s3
          runs-on: ubuntu-latest
          needs: build #makes sure this job runs after build job is complete
          env: 
            AWS_ACCESS_KEY_ID:  ${{ secrets.aws_access_key }} #Ginger Templating -
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.aws_secret_key }}
            AWS_REGION: "us-east-1"
          steps:
            - name: download artifact 
              uses: actions/download-artifact@v3
              with:
                name: my-artifact
                path: package

            - name: deploy package
              run: aws s3 cp package/*.war s3://application-source-code-bucket