name: provision three tier architecture using terraform

on: 

    workflow_dispatch:

jobs:
    provision-three-tier:
        runs-on: ubuntu-latest
        env:
            PKR_VAR_region: us-east-1
            AWS_ACCESS_KEY_ID:  ${{ secrets.aws_access_key }} #Ginger Templating
            AWS_SECRET_ACCESS_KEY:  ${{ secrets.aws_secret_key }}
            TF_VAR_db_password: ${{ secrets.db_password }}
            TF_VAR_db_username: ${{ secrets.db_user_name }}

        steps:
            - name: checkout
              uses: actions/checkout@v3  #checkout is Github plugin
    
            - name:  setup terraform  #provide Terraform binanries - install terraform
              uses: hashicorp/setup-terraform@v3
    
            - name: terraform initialize
              run: terraform init
    
            - name: terraform format and validate
              run: |
                terraform fmt
                terraform validate
    
            - name: terraform plan #(terraform plan command)it will keep on executing to disable loop, we add '-input=false'
              run: terraform plan -input=false -lock=false 
    
            - name: terraform apply 
              run: terraform apply --auto-approve -lock=false

            - name: terraform destroy 
              run: terraform destroy --auto-approve -lock=false
    
              

